#!/bin/bash

# 🚀 Setup Users Table for GitHub OAuth
# This script helps you create the users table in Supabase

echo "🚀 Setting up Users Table for GitHub OAuth"
echo "=========================================="

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    echo "❌ Error: Please run this script from the project root directory"
    echo "   Current directory: $(pwd)"
    echo "   Expected: /Users/josualeonard/bookipi/github-reward-coin"
    exit 1
fi

echo "✅ Project directory found: $(pwd)"

echo ""
echo "📋 Next Steps:"
echo "=============="
echo ""
echo "1. 🌐 Go to Supabase Dashboard:"
echo "   https://supabase.com/dashboard"
echo ""
echo "2. 🎯 Select your project:"
echo "   Project: uvkwcralkuwqocgsmcap"
echo ""
echo "3. 📝 Go to SQL Editor (left sidebar)"
echo ""
echo "4. 📋 Copy and paste this SQL:"
echo ""
echo "   -- Create the users table for storing GitHub user data"
echo "   CREATE TABLE IF NOT EXISTS users ("
echo "     id TEXT NOT NULL PRIMARY KEY,"
echo "     github_token TEXT,"
echo "     github_username TEXT,"
echo "     github_id BIGINT,"
echo "     email TEXT,"
echo "     wallet_address TEXT, -- Crypto wallet address format"
echo "     accumulated_reward DECIMAL(18,8) DEFAULT 0, -- Accumulated amount of crypto"
echo "     created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),"
echo "     updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()"
echo "   );"
echo ""
echo "   -- Grant necessary permissions"
echo "   GRANT ALL ON users TO anon;"
echo "   GRANT ALL ON users TO authenticated;"
echo "   GRANT ALL ON users TO service_role;"
echo ""
echo "   -- Create indexes for better performance"
echo "   CREATE INDEX IF NOT EXISTS idx_users_github_id ON users(github_id);"
echo "   CREATE INDEX IF NOT EXISTS idx_users_github_username ON users(github_username);"
echo "   CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);"
echo "   CREATE INDEX IF NOT EXISTS idx_users_wallet_address ON users(wallet_address);"
echo "   CREATE INDEX IF NOT EXISTS idx_users_accumulated_reward ON users(accumulated_reward);"
echo ""
echo "5. ▶️  Click 'Run' to execute the SQL"
echo ""
echo "6. ✅ You should see 'Success. No rows returned'"
echo ""
echo "7. 🧪 Test the fix:"
echo "   yarn server:stop"
echo "   yarn server"
echo ""
echo "8. 🔗 Test OAuth flow:"
echo "   curl -I http://localhost:54321/functions/v1/connect/github"
echo ""
echo "📚 For more details, see: documentation/USERS-TABLE-SETUP.md"
echo ""
echo "🎉 Once the table is created, your GitHub OAuth will work completely!"
